### PR TITLE
feat(llm): rename env variable for BAM provider

### PR DESCRIPTION
**Pull request by Tomas2D**

### CODE REVIEW

**Review by jezekra1 — APPROVED** [review]

**Review by pilartomas — CHANGES_REQUESTED** [review]
What's the motivation for this change? If naming changes it should change everywhere, not just this variable.

**Comment by Tomas2D** [comment]
We are about to change it everywhere (like other projects), but we initially started with `GENAI_API_KEY` in our NodeJS SDK, so we think we should keep using it.

**Comment by pilartomas** [comment]
Does that mean that the BAM adapter in the framework will be renamed to GenAI adapter? Then let's do it in one sweep once it's ready. Changing just the env would cause mismatch with the `LLM_BACKEND`, `EMBEDDING_BACKEND` envs and also naming mismatch within the codebase.

**Comment by Tomas2D** [comment]
The framework uses SDK directly; hence, it takes `GENAI_API_KEY` only (the framework does not read ENV directly, but SDK does).

**Comment by pilartomas** [comment]
In the API, the SDK involvement is an internal thing, not an interface.

The user sets `LLM_BACKEND=bam` env variable referencing framework's BAM adapter and sets `BAM_API_KEY` credential. The key is also picked up from the BAM service. Naming it `GENAI` would be confusing in this setup.

Note that `GENAI_API_KEY` env will still be picked up if `BAM_API_KEY` hasn't been specified, but that is more of a hidden feature we might guard against in the future.

**Comment by jezekra1** [comment]
Closing for inactivity

**Pull request closed without merging**
